### ISSUE TITLE
Border wall gravel glitch i guess...

### ISSUE THREAD

**Issue by iTzKillaPlaysMC** [AmauryCarrade/UHPlugin#111]
So i generated the walls but aparently there was some gravel and when it falled it didn't generate glass on there thats just my guess i just saw this on the wall
![2015-07-18_07 48 15](https://cloud.githubusercontent.com/assets/8517863/8761493/f1b738fc-2d21-11e5-9eaf-f76424f298e0.png)
Thanks.

**Comment by iTzKillaPlaysMC** [comment]
Nvm is not the gravel its just all arround the wall there is lots and lots of holes in water pots only idk if this is a feature or something...

**Comment by iTzKillaPlaysMC** [comment]
Ok... sorry for posting fast but found a solution and prob the problem, it can be fixed by doing the command again and i am pretty sure it occurred while that part of the world was still generating so the sand was falling to its position and gravel too so yeah prob want to generate chunks before generating the walls i guess i am pretty sure there is a way of doing so in code. 
Thanks

**Comment by jonyroda97** [comment]
Have you pre generated the chunks with <code>/wb fill </code> before doing the wall?
If you have the plugin worldborder it doesn't matter cause the players will be teleported to inside the walls.

**Comment by AmauryCarrade** [comment]
The problem is that Minecraft populates the terrain after the wall generation, so these lakes and other trees cut the wall (the hole is the air blocks sets by the Minecraft world populator above the lakes).

Fully generate the world before generating the wall to avoid this problem (as mentioned in the installation notes).
Re-generating the wall again will only fix the problem on the populated (i.e. visited, if you did not generated the world between the generation) chunks of the world.
