### ISSUE TITLE
Use a more explicit error message for cmd.errorUnauthorized (en/fr/pt/br)

### ISSUE THREAD

**Issue by prokopyl** [AmauryCarrade/UHPlugin#80]
Currently, a non-op player receives the message "lolnope" when he tries to use an op command.
This is not much, but it is extremely confusing.

**Comment by AmauryCarrade** [comment]
I never changed that in fact :p . But yes, you're right. I'll update the French and English translations with a better text.

See with @jonyroda97 for the pt_PT translation.

**Comment by Amunak** [comment]
uh, can't you use the default server message? You don't need to check for op yourself I believe, you can keep permissions and stuff on the server's implementation.

**Comment by jonyroda97** [comment]
Will update it tomorrow.

@eraizel can you update the pt_BR translation too?
(English translation is there already, see commits)

@AmauryCarrade message for you above :smiley:

**Comment by AmauryCarrade** [comment]
@jonyroda97 The pt_BR translation is not already correct? See https://github.com/AmauryCarrade/UHPlugin/blob/master/src/main/resources/i18n/pt_BR.yml#L29

@Amunak Yes I use the Bukkit method to get permissions, but I still need to do something if the permission is not granted (here, return an error message). I don't know if there is a message for « access not granted » available in the API, but even if one is available, because I want this message to be translated, I prefer using the translation file :) .

**Comment by Amunak** [comment]
Oh never mind you are right, of course you have to provide your own mess-

Wait, [there is something](http://wiki.bukkit.org/Plugin_YAML) (see permission-message there). So there should be *some* way to let bukkit handle this (and when it's not set the server would use the global error message). But it's probably for some standardized way of registering commands I guess. Perhaps if you had commands with permissions in plugin.yml it would work. Oh yeah. I read somewhere some time ago that returning false or something in a command listener would tell bukkit to display the no permission message.

Personally I like it since ideally you have it set server-wide and it's always the same, but I can understand the appeal of having it easily(ish) configurable.

**Comment by AmauryCarrade** [comment]
Even with that, I don't think I can use that, because I only use one command (mainly) and a lot of permissions for sub-commands. But for other plugins, I keep the possibility in mind :) .

**Comment by jonyroda97** [comment]
In English the pt_BR says "not here aligator"
I think that it's not the translation that you want :smiley:

**Comment by Amunak** [comment]
Yeah you are right, that's exactly the same dillema I had when I wrote 
my plugins (it has just been so long that I don't even remember lol). I 
definitely prefer having a single command that uses parameters to group 
subcommands and stuff because otherwise just typing a slash and using 
autocompletion becomes a horrible unmanageable mess.

**Comment by jonyroda97** [comment]
pt_PT  ------   CHECK!! :smile:

@AmauryCarrade  talk with @eraizel about the pt_BR translation

**Comment by eraizel** [comment]
I am doing it right now! I was in holidays! LOL

**Comment by eraizel** [comment]
I have corrected it but when I saw it at the first time I also though was not very informative and changed with a funny expression! I have updated accordingly now with the english version!
