### ISSUE TITLE
Tab and life

### ISSUE THREAD

**Issue by rogama25** [AmauryCarrade/UHPlugin#93]
I think that is better to show the life in hearths (<3<3<3<3<3) than in points (10) Why not to add this as default and then an option to use the old method.
And please look to an update posted by me in issue #91.

**Comment by AmauryCarrade** [comment]
Already the case... if you use the 1.8 version of the game (and the server, the hearts are not displayed with Spigot 1.7+1.8 due to Spigot).

See (with Spigot 1.8 and the version 1.2 (well, a few builds before the official release to be honest)):
![uhplugin_lifesintab](https://cloud.githubusercontent.com/assets/1417570/6517053/87b7cc9e-c397-11e4-92ce-edbd7586e167.png)

Or I misunderstood something?

**Comment by rogama25** [comment]
Yeah it's just what I want. I'm using a spigot precompiled jar that I found on a video on Youtube. I'll try this. Thanks
