### ISSUE TITLE
Warning msg when /wb fill was not done

### ISSUE THREAD

**Issue by eraizel** [AmauryCarrade/UHPlugin#94]
> After the installation, I recommend you to:
> 
> 1. teleport yourself to 0,0 (in creative, /tp 0 100 0);
> 2. set the world spawn point here (/setworldspawn);
> 3. reload the server (for the plugin to take into account the change) (/rl);
> 4. pregenerate the entire world (WorldBorder is preconfigured, just execute /wb fill);
> 5. only after that, generate the wall (/uh generatewalls) (don't forget to configure the shape and the size 6. in the config file before). Otherwise, holes will be formed in the wall when Minecraft will populate the terrain.

By mistake I haven't done the `/wb fill` and I was doing direct step 5

and it says that the command does not exist or there is a sintax error I think there should be a little warning about `/wb fill` was not performed?

**Comment by AmauryCarrade** [comment]
> and it says that the command does not exist or there is a sintax error

It said that for what command? `/uh generatewalls` (you probably miswritten it, use the autocompletion), or /wb fill`?

> I think there should be a little warning about /wb fill was not performed?

Technically difficult, because it's not my plugin behind `/wb fill`, it's WorldBorder. And I don't think there is a way to detect a whole map is generated... I'll look at this, but I don't promise anything.

**Comment by eraizel** [comment]
the problem only happen when you by mistake don't use /wb fill 
if you jump /wb fill as an step and go direct to /uh generatewalls you don't get a message warning you about your mistake it does not recognize the /uh generatewalls at all

**Comment by AmauryCarrade** [comment]
The fact that `/uh generatewalls` is not recognized is weird. I never had this comportment before.
This is very probably totally unrelated to the fact that `/wb fill` was executed before or not.

Hmm. Are you using the latest development builds? You should not at the moment, because I'm rewriting the way the commands are managed, so they are broken.

Well, in fact, please give me the version and build number of the version you are using, [as explained here](https://github.com/AmauryCarrade/UHPlugin/blob/dev/CONTRIBUTING.md#bugs).

**Comment by jonyroda97** [comment]
I'm sure that it works without the <code>/wb fill</code>.
Are you sure that you have done it with the <code>/uh generatewalls</code> and not with <code>/uh border generatewalls</code> (I have done it one time :smile:)
